### ISSUE TITLE
Additional Github Actions

### ISSUE THREAD

**Issue by dtq-one** [DATATRONiQ/node-red-contrib-iiot-opcua#6]
## Feature

 - (x) feature request
 
 **What is the motivation or Use Case for your feature request?**

We strive to leverage as many useful GH action as possible in order to minimize the administrative/organizational effort in managing this FOSS project and maximize the overall utility of the solution for the users by keeping the code base free of bugs, easily readable and understandable (well structured, well tested, well documented).

## Tasks

- [ ] review https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
- [ ] in particular review section of recommended GH action at bottom of https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
- [ ] discuss what additional GH actions are useful or our purpose

**Comment by ghost** [comment]
This issue has been closed to migrate Issues to the BiancoRoyal repository and can now be found [here](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/issues/134)
