### ISSUE TITLE
Publish nodes to npmjs

### ISSUE THREAD

**Issue by dtq-one** [DATATRONiQ/node-red-contrib-iiot-opcua#7]
## Background

Currently, older versions of `node-red-contrib-iiot-opcua` are published at https://www.npmjs.com/package/node-red-contrib-iiot-opcua. However, the original maintainer "biancode" decided to take the project offline/private. 

In order for existing and new users to benefit from the latest versions of "new" node-red-contrib-iiot-opcua, it is desirable to be able to publish to npmjs as the node-red-contrib-iiot-opcua project.

https://docs.npmjs.com/policies/disputes#tldr ( found at: https://stackoverflow.com/a/54079359 )

>   1. Open a support ticket at https://npmjs.com/support
>   2. Explain why you require a package, org, or username transferred
>   3. Support will address your request. Please note submitting a report does not guarantee the transfer of a package, org, or username.

## Tasks

- [ ] contact original maintainer about collaboration and discuss access to node-red-contrib-iiot-opcua on npmjs
- [ ] optional: discuss new package name and project on GH and npmjs
- [ ] Automatically publish to NPM when committing to a tag or committing to main (TBD).

**Comment by ghost** [comment]
Closed in favor of tracking in the BiancoRoyal/ repository [here](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/issues/136)
